version: '3'

services:
  mox:
    build: .
    container_name: mox
    hostname: ${MOX_HOSTNAME}
    restart: unless-stopped
    command: serve
    environment:
      - MOXCONF=/mox/config/mox.conf
    volumes:
      - ${MOX_ROOT}/data:/mox/data
      - ${MOX_ROOT}/config:/mox/config
    ports:
      - "25:25"     # SMTP
      # - "110:110"   # POP3
      # - "143:143"   # IMAP
      - "443:443"   # HTTPS
      - "465:465"   # Submissions
      # - "587:587"   # Submission
      - "993:993"   # IMAPS
      # - "995:995"   # POP3S
      - "4190:4190" # Sieve
